import pygame

redAmber=pygame.image.load("./Assets/TL A R.png")
red=pygame.image.load("./Assets/TL R.png")
amber=pygame.image.load("./Assets/TL A.png")
green=pygame.image.load("./Assets/TL G.png")
road=pygame.image.load("./Assets/road.png")
binny=pygame.image.load("./Assets/bin.png")
tJunct=pygame.image.load("./Assets/Junction T.png")
fourJunct=pygame.image.load("./Assets/Junction +.png")
splitJunct=pygame.image.load("./Assets/Junction Split.png")
rotateImg=pygame.image.load("./Assets/Rotate.png")
edit=pygame.image.load("./Assets/Edit Tool.png")
timey=pygame.image.load("./Assets/Time.png")

BACKGROUND=pygame.Color("#EAEAEA")
BLUE=pygame.Color("#00A896")     
OFFBLUE=pygame.Color("#88CCCC")
ORANGE=pygame.Color("#89043D")
LB=pygame.Color("#2FE6DE")
BLACK=pygame.Color("#000000")
PINK=pygame.Color("#FF1493")
REALORANGE=pygame.Color("#FF8C00")
REALBLUE=pygame.Color("#0000A0")
GREEN=pygame.Color("#228B22")